name: Build

on:
  push:
    branches: [ "master" ]
  release:
    types: [published]

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - arch: amd64
            distro: ubuntu_latest
          - arch: arm64
            distro: ubuntu_latest
          - arch: riscv64
            distro: ubuntu_latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: go get .
      - name: Build fully static artifact
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=${{ matrix.arch }} go build -o ssh-${{ matrix.arch }} -ldflags="-s -w" main.go
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ssh-${{ matrix.arch }}
          path: ssh-${{ matrix.arch }}
      - name: Upload Release Asset
        if: github.event_name == 'release'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} ./ssh-${{ matrix.arch }} --clobber
